version: '3'
services:
  back-end:
    build:
      context: demo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  front-end:
    build:
      context: FRONT-END
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - back-end
